ifneq ($(KERNELRELEASE),)
  obj-m := kernel_hypercall.o 

else
        KERNELDIR ?= /lib/modules/$(shell uname -r)/build
        PWD := $(shell pwd)

default:
	$(MAKE) -C $(KERNELDIR) M=$(PWD) modules
endif

clean:
	rm *.o *.ko modules.order Module.symvers
